#PBS -N test
#PBS -l nodes=1:ppn=16
#PBS -q batch
#PBS -V
#PBS -S /bin/bash 
### Set intel environment###
source /opt/env/intel2019u5.sh
cd $PBS_O_WORKDIR
NP=`cat $PBS_NODEFILE | wc -l`
NN=`cat $PBS_NODEFILE | sort | uniq | tee /tmp/nodes.$$ | wc -l`
cat $PBS_NODEFILE > /tmp/nodefile.$$
mpirun -machinefile /tmp/nodefile.$$ -n $NP /opt/software/vasp.5.4.4/bin/vasp_std
rm -rf /tmp/nodefile.$$
rm -rf /tmp/nodes.$$